apiVersion: v1
kind: ConfigMap
metadata:
  name: vlender-configmap-urls
  namespace: vlender-ns
  labels:
    app: vlender-application
    subname: configmap
data:
  urlLoanservice: http://vlender-loan:9090/loan
  urlUserservice: http://vlender-user:9090/user
  urlCustomerprofileservice: http://vlender-customerprofile:9090/customerprofile
  urlOpenbankingservice: http://vlender-openbanking:9090/openbanking
  urlBigbankservice: http://vlender-bigbank:9090/bigbank
  urlGreatbankservice: http://vlender-greatbank:9090/greatbank
  urlCreditscoreservice: http://vlender-creditscore:9090/creditscore
  urlLoanprocessorservice: http://vlender-loanprocessor:9090/loanprocessor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vlender-configmap-db
  namespace: vlender-ns
  labels:
    app: vlender-application
    subname: configmap
data:
  # ## DB2
  # datasourceUrl: jdbc:db2://1.2.3.4:12345/vlender
  # datasourceUserName: 1
  # datasourcePassword: 1
  # datasourceDriverClassName: com.ibm.db2.jcc.DB2Driver
  # datasourceJpaDatabasePlatform: org.hibernate.dialect.DB2Dialect

  # ## MySql
  # datasourceUrl: jdbc:jdbc:mysql://1.1.1.1:3306/vlender
  # datasourceUserName: 1
  # datasourcePassword: 1

  ## H2
  datasourceUrl: jdbc:h2:mem:/vlender
  datasourceUserName: admin
  datasourcePassword: admin
  datasourceDriverClassName: org.h2.Driver
  datasourceJpaDatabasePlatform: org.hibernate.dialect.H2Dialect
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vlender-configmap-mq
  namespace: vlender-ns
  labels:
    app: vlender-application
    subname: configmap
data:
  greatbankMqQueueManager: qmgr
  greatbankMqConnName: vlender-qm-ibm-mq.banking(1414)
  greatbankMqChannel: DEV.APP.SVRCONN
  greatbankMqQueueNameRequestLoanOffer: DEV.QUEUE.1
  greatbankMqQueueNameRequestLoanDetail: DEV.QUEUE.2
  greatbankMqQueueNameRequestTransHistory: DEV.QUEUE.3
  greatbankMqQueueNameRequestLoanHistory: PROD.QUEUE.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vlender-configmap-eventstream
  namespace: vlender-ns
  labels:
    app: vlender-application
    subname: configmap
data:
  iLenderEventstreamTopicRequestLoanOffer: vlender-request-loan-offer
  iLenderEventstreamTopicRequestLoanDetail: vlender-request-loan-detail
  iLenderEventstreamTopicNotifyLoanRequestApproved: vlender-notify-loan-request-approved
  iLenderEventstreamTopicNotifyLoanOfferAccepted: vlender-notify-loan-offer-accepted
  iLenderEventstreamTopicNotifyLoanRequestCreated: vlender-notify-loan-request-created
  iLenderEventstreamServerUrl: eventstreams-kafka-bootstrap-integration.gsidemos-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.us-south.containers.appdomain.cloud:443
  iLenderEventstreamTruststoreLocation: /opt/vlender-eventstream.jks
  iLenderEventstreamTruststorePassword: changeit
  iLenderEventstreamSCRAMUserName: vlender
  iLenderEventstreamSCRAMPassword: test
  iLenderKafkaEnabled: "false"
  iLenderNotifyEnabled: "false"
  iLenderApiConnectEnabled: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vlender-configmap-common
  namespace: vlender-ns
  labels:
    app: vlender-application
    subname: configmap
data:
  logType: DEFAULT
  # logType: LOG_DNA
  # logType: HUMIO
  logHost: ocp-gsi
  humioUrl: http://1.1.1.1:8080/api/v1/ingest/humio-unstructured
  humioToken: AAA
  logdnaUrl: https://logs.us-south.logging.cloud.ibm.com/logs/ingest
  logdnaToken: "1111"
  loadSimulation: "TRUE"
  increaseSizeInKB: "50240"
  maxIncreaseSizeInKB: "500240"
  initialSleepMilliSeconds: "300000"
  incrementSleepMilliSeconds: "1000"
  incrementSleepForRequest: "1"
---
