apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlender-greatbank
  namespace: vlender-ns
  labels:
    app: vlender-application
    subname: greatbank
spec:
  selector:
    matchLabels:
      app: vlender-application
      subname: greatbank
  replicas: 1
  template:
    metadata:
      labels:
        app: vlender-application
        subname: greatbank
    spec:
      containers:
        - name: container-greatbank
          image: "gandigit/ilender-greatbank-demo:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: my-http
              containerPort: 9079
              protocol: TCP
            - name: https
              containerPort: 8082
          # resources:
          #   requests:
          #     memory: "500Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "1024Mi"
          #     cpu: "500m"
          # livenessProbe:
          #   httpGet:
          #     path: /greatbank
          #     port: my-http
          #   initialDelaySeconds: 120
          # failureThreshold: 6
          # readinessProbe:
          #   httpGet:
          #     path: /greatbank
          #     port: my-http
          #   initialDelaySeconds: 120
          env:
            - name: MY_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_CONTAINER_NAME
              value: container-greatbank
            - name: MY_CONTAINER_IMAGE
              value: "gandigit/ilender-greatbank-demo:0.0.1"
            - name: MY_LABELS_APP
              value: greatbankservice
            - name: MY_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: skipExternalLog
              value: "TRUE" 
          envFrom:
            - configMapRef:
                name: vlender-configmap-urls
            - configMapRef:
                name: vlender-configmap-db
            - configMapRef:
                name: vlender-configmap-mq
            - configMapRef:
                name: vlender-configmap-eventstream
            - configMapRef:
                name: vlender-configmap-common

---
apiVersion: v1
kind: Service
metadata:
  name: vlender-greatbank
  namespace: vlender-ns
  labels:
    app: vlender-application
    subname: greatbank
spec:
  type: LoadBalancer
  ports:
    - name: my-http
      port: 9090
      targetPort: my-http
  selector:
    app: vlender-application
    subname: greatbank
